apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jerney-db-pvc
  labels:
    app.kubernetes.io/part-of: {{ .Chart.Name }}
    app.kubernetes.io/component: database
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.storageClass.name }}
  resources:
    requests:
      storage: {{ .Values.db.storage }}
